### ISSUE TITLE
这个不支持双向通信吗？

### ISSUE THREAD

**Issue by bundery** [wrxiang/WebRunLocal#1]
比如本地软件利用 webscoket 推送消息给 web

**Comment by wrxiang** [comment]
不支持，个人不建议直接和网页做交互，如果本地程序要反向推送消息的话建议和后台程序做接口，然后后台程序和网页交互，业务处理都放在后台

**Comment by wrxiang** [comment]
暂不支持，之后可以考虑把这个功能加上
