### ISSUE TITLE
请大神提供一下html文件

### ISSUE THREAD

**Issue by swifttao** [wrxiang/WebRunLocal#2]
readme.md文件中提到这个  WebRunLocal测试.html
我在项目目录下面未发现，请问您可以更新一下嘛

**Comment by wrxiang** [comment]
https://github.com/wrxiang/WebRunLocal/releases
下载发布版本，里面有测试的网页，只是一个简单的http请求，没有放在源码中

**Comment by wrxiang** [comment]
已提交，放在bin/Debug目录下了
