### ISSUE TITLE
没看见exe文件

### ISSUE THREAD

**Issue by hlgf** [wrxiang/WebRunLocal#6]
老哥，这个程序怎么跑呀，没看见exe文件

**Comment by wrxiang** [comment]
https://github.com/wrxiang/WebRunLocal/releases
这里可以下载编译后的文件，源代码在VS中运行，是基于C#开发 的

**Comment by wrxiang** [comment]
> 老哥，这个程序怎么跑呀，没看见exe文件

https://github.com/wrxiang/WebRunLocal/releases
这里可以下载编译后的文件，源代码在VS中运行，是基于C#开发 的

**Comment by wrxiang** [comment]
> 老哥，这个程序怎么跑呀，没看见exe文件

https://github.com/wrxiang/WebRunLocal/releases
这里可以下载编译后的文件，源代码在VS中运行，是基于C#开发 的
